/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.NEOManager;

import Network.Network;
import business.Enterprise.Enterprise;
import business.Enterprise.Orphane;
import business.Enterprise.Restaurant;
import business.UserAccount.UserAccount;
import business.WorkQueue.OrphaneRequest;
import business.business.EcoSystem;
import java.io.ObjectOutputStream;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liuch
 */
public class NEOManegerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form NEOManegerWorkArea
     */
    EcoSystem system;
     JPanel userProcessContainer;
    UserAccount userAccount;
    Network network;
    Orphane enterprise;
     ObjectOutputStream streamOut;
    public NEOManegerWorkArea(EcoSystem system,JPanel userProcessContainer,UserAccount userAccount,Network network,Enterprise enterprise, ObjectOutputStream streamOut) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.network = network;
        this.enterprise = (Orphane)enterprise;
        this.system = system;
        this.streamOut = streamOut;
        lableNGOName.setText(enterprise.getName());
        System.out.println(network);
       
       
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lableNGOName = new javax.swing.JLabel();

        jLabel1.setText("Number Of Food:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Send request for food");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lableNGOName.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableNGOName)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(576, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lableNGOName)
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addContainerGap(340, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Restaurant r=(Restaurant)jComboBox1.getSelectedItem();
         OrphaneRequest request = new OrphaneRequest(network,enterprise);
         Date current = new Date();
         request.setRequestDate(current);
         request.setSender(userAccount);
         request.setNumberOfFood(Integer.parseInt(jTextField1.getText()));
         request.setStatus("Send to restaurant");
         userAccount.getWorkQueue().getWorkRequestList().add(request);
         network.getQueueOphan().getWorkRequestList().add(request);
        // r.getQueueOphan().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Request Send out");
        try{
               streamOut.reset();
               streamOut.writeObject(system);
               streamOut.flush();
           }catch(Exception e){
               System.out.print("Exception"+e.getMessage());
           }
         System.out.println(network.getQueueOphan().getWorkRequestList().size());
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lableNGOName;
    // End of variables declaration//GEN-END:variables
}
