/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SuperMarketManager;

import SuperMarketItem.SuperMarketItem;
import business.Enterprise.SuperMarket;
import business.business.EcoSystem;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liuch
 */
public class ManageDiscountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDiscountJPanel
     */
    EcoSystem system;
    SuperMarket superMarket;
    JPanel userProcessContainer;
    Connection con;
    public ManageDiscountJPanel(EcoSystem system,SuperMarket superMarket,JPanel userProcessContainer) {
        initComponents();
        this.system = system;
        this.superMarket = superMarket;
        this.userProcessContainer = userProcessContainer;
        populateTable();
    }
    public ArrayList<SuperMarketItem> superMarketItemList(){
        ArrayList<SuperMarketItem> list = new ArrayList<>();
        try{
           /* Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://35.185.14.219:3306;databaseName=new_schema;user=root;password=8466";
            Connection con = DriverManager.getConnection(url);*/
             String DB_URL = "jdbc:mysql://35.185.14.219:3306/new_schema";
             String DB_DRV =  "com.mysql.jdbc.Driver";
             String DB_USER = "root";
            String DB_PASSWD = "8466";
            con=DriverManager.getConnection (DB_URL,DB_USER,DB_PASSWD);
            String query1 = "SELECT * FROM new_schema.`"+superMarket.getUserAccount().getUsername()+"`";
            Statement st = (Statement)con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            SuperMarketItem item;
            while(rs.next()){
               item = new SuperMarketItem(rs.getInt("id"),rs.getString("Name"),rs.getInt("calorie"),rs.getDouble("Price"),rs.getBytes("pic"),rs.getDouble("discount"),rs.getInt("inventory"),rs.getInt("saleHistory"));
               list.add(item);
            }
    }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        return list;
    }
    public void populateTable()
{
   /*  DefaultTableModel model = (DefaultTableModel) tblManu.getModel();
     model.setRowCount(0);
     for (RestaurantDish rd :restaurant.getMenu().getMenuList()){
            Object[] row = new Object[2];
            row[0] = rd;
            row[1] = rd.getPrice();
            model.addRow(row);
        }
    */
    ArrayList<SuperMarketItem> list = superMarketItemList();
      // jTable1.getColumnModel().getColumn(2).setCellRenderer(jTable1.getDefaultRenderer(ImageIcon.class));
       DefaultTableModel model =(DefaultTableModel) tblManu.getModel();
        model.setRowCount(0);
       //if(list.size()>1)
           
      // jLabel4.setIcon(new ImageIcon(list.get(1).getPic()));
      /* {ImageIcon a = new ImageIcon(list.get(1).getPic());
        Image image = a.getImage();
        double h = 100.0/a.getIconHeight();
        Image newimg = image.getScaledInstance((int)(a.getIconWidth()*h), (int)(a.getIconHeight()*h),java.awt.Image.SCALE_SMOOTH);
        ImageIcon newone= new ImageIcon(newimg);
        jLabel4.setIcon(newone);
       }*/
       Object[] row = new Object[7];
       for(int i=0;i<list.size();i++)
       {
           row[0] = list.get(i).getId();
           row[1] = list.get(i);
           row[2] = list.get(i).getCalorie();
           row[3] = list.get(i).getPrice();
           row[4] = list.get(i).getDiscount();
           row[5] = list.get(i).getInventory();
           row[6] = list.get(i).getSaleHistory();
        //   row[2] = new ImageIcon(list.get(i).getPic());
          // row[2] = new ImageIcon([B@72d5d89e);
           //System.out.println("after read"+list.get(i).getPic());
           model.addRow(row);
       }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManu = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jRadioButtonSuggested = new javax.swing.JRadioButton();
        jRadioButtonCustomeized = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        tblManu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Calorie", "Price", "Discount", "Inventory", "SaleHistory"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblManu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblManuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblManu);

        jTextField1.setEditable(false);

        jButton1.setText("Make a discount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSuggested);
        jRadioButtonSuggested.setText("Suggested Discount:");
        jRadioButtonSuggested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSuggestedActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCustomeized);
        jRadioButtonCustomeized.setText("Customized Discount:");
        jRadioButtonCustomeized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomeizedActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonSuggested)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonCustomeized)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(69, 69, 69)
                        .addComponent(jButton1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonSuggested))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCustomeized)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(438, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private double suggestedDiscount(SuperMarketItem item)
    {
        double discount =0;
        if(item.getInventory()==0)
            return 0;
        
        else if( item.getSaleHistory()/item.getInventory() <0.1)
       {
           return 0.6;
       }
       else if(item.getSaleHistory()/item.getInventory() <0.3)
       {
           return 0.5;
       }
        else if(item.getSaleHistory()/item.getInventory() <0.5)
       {
           return 0.1;
       }
       else
            return 0;
            
    }
    private void tblManuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblManuMouseClicked
        int i = tblManu.getSelectedRow();
        //new ImageIcon(list.get(i).getPic());
        SuperMarketItem item = (SuperMarketItem)tblManu.getValueAt(i,1);
        jTextField1.setText(String.valueOf(suggestedDiscount(item)));      // TODO add your handling code here:
    }//GEN-LAST:event_tblManuMouseClicked

    private void jRadioButtonSuggestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSuggestedActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSuggestedActionPerformed

    private void jRadioButtonCustomeizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomeizedActionPerformed
             // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCustomeizedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double discount =0;
        if(jRadioButtonCustomeized.isSelected())
        {
            try{
                discount = Double.parseDouble(jTextField2.getText());
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Input currect number");
                return;
            }
            if(!(0<discount)&&(discount<1))
            {
                JOptionPane.showMessageDialog(null, "Wrong range for discount");
                return;
            }
        }
        else  if(jRadioButtonCustomeized.isSelected())
            discount = Double.parseDouble(jTextField1.getText());
        else{
            JOptionPane.showMessageDialog(null,"Please select");
            return;
        }
    
       int i = tblManu.getSelectedRow();
        if(i<0)
     {
         JOptionPane.showMessageDialog(null,"Please select");
         return;
     }
        //new ImageIcon(list.get(i).getPic());
     
         SuperMarketItem item = (SuperMarketItem)tblManu.getValueAt(i,1);
     
     int id = item.getId();
     String query1 = "UPDATE `new_schema`.`"+superMarket.getUserAccount().getUsername()+"` SET `discount`='"+discount+"' WHERE `id`='"+id+"';";
     Statement st;
        try {
            st = (Statement)con.createStatement();
            st.executeUpdate(query1);
            JOptionPane.showMessageDialog(null,"Discount updated");
            populateTable();
            
        } catch (SQLException ex) {
            Logger.getLogger(ManageDiscountJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jRadioButtonCustomeized;
    private javax.swing.JRadioButton jRadioButtonSuggested;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblManu;
    // End of variables declaration//GEN-END:variables
}
