/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import business.Enterprise.Restaurant;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import business.business.EcoSystem;
import java.awt.CardLayout;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import picutill.OnlineDish;

/**
 *
 * @author liuch
 */
public class MyOrder extends javax.swing.JPanel {

    /**
     * Creates new form MyOrder
     */
    EcoSystem system;
    JPanel userProcessContainer;
    UserAccount userAccount;
    ObjectOutputStream streamOut;
    public MyOrder(EcoSystem system,JPanel userProcessContainer,UserAccount userAccount,ObjectOutputStream streamOut) {
        initComponents();
        this.system = system;
         this.userProcessContainer=userProcessContainer;
         this.userAccount = userAccount;
         this.streamOut = streamOut;
         populateTable();
         
    }
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
        
       for(WorkRequest r:userAccount.getTheOrderIsentoutQueue().getWorkRequestList()) {
           Object row[] = new Object[4];
           row[0] = r;
           row[1] = r.getRequestType();
           row[2]=r.getStatus();
           row[3] = timeSince(r.getRequestDate());
            model.addRow(row);
        
         }  
    
    
}
    public String timeSince(Date requestDate){
        
        Date current = new Date();
        long diff = current.getTime() - requestDate.getTime();
        long diffMinutes = diff / (60 * 1000);   
        return String.valueOf(diffMinutes);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Order Type", "Status", "Time Since Request Sent out"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Approve Order Finished");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("<<Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(296, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //这里写两个功能，一个是把订单确认，并且从顾客的workqueue和deliveryman的workqueue里删除
    //另外一个是跳转到makecommend页面并且确认
    int selectedRow=jTable1.getSelectedRow();
     if(selectedRow<0)
     {
         JOptionPane.showMessageDialog(null,"Please select");
         return;
     }
     WorkRequest r= (WorkRequest)jTable1.getValueAt(selectedRow,0);
     r.setStatus("Received");
     userAccount.getTheOrderIsentoutQueue().getWorkRequestList().remove(r);
     r.getDeliveryMan().getWorkQueue().getWorkRequestList().remove(r);
     JOptionPane.showMessageDialog(null,"Reveived");
     populateTable();
     try{
     streamOut.reset();
     streamOut.writeObject(system);
    // System.out.println("********"+system.getNetworkList().get(0).getUserList().getUserAccountList().get(0).getTheOrderIsentoutQueue().getWorkRequestList().size());
     streamOut.flush();
     }catch(Exception exception){
         System.out.println("Error:"+exception.getMessage());
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
