/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SuperMarketManager;

import Network.Network;
import business.Enterprise.Enterprise;
import business.Enterprise.SuperMarket;
import business.UserAccount.UserAccount;
import business.business.EcoSystem;
import java.awt.CardLayout;
import java.io.ObjectOutputStream;
import javax.swing.JPanel;
import userInterface.RestaurantManagerRole.ManageRequestJPanel;

/**
 *
 * @author liuch
 */
public class ManageSuperMarketWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuperMarketWorkAreaJPanel
     */
    UserAccount account;
    EcoSystem system;
    SuperMarket superMarket;
    Network network;
    JPanel userProcessContainer;
    ObjectOutputStream streamOut;
    public ManageSuperMarketWorkAreaJPanel(UserAccount account,EcoSystem system,Enterprise enterprise,Network network,JPanel userProcessContainer, ObjectOutputStream streamOut) {
        initComponents();
        this.account = account;
        this.system = system;
        this.superMarket =(SuperMarket) enterprise;
        this.network = network;
        this.userProcessContainer = userProcessContainer;
        this.streamOut = streamOut;
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageManu = new javax.swing.JButton();
        btnManageOrder = new javax.swing.JButton();
        btnManageManu1 = new javax.swing.JButton();

        btnManageManu.setText("Manage Fruit and VegiList");
        btnManageManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageManuActionPerformed(evt);
            }
        });

        btnManageOrder.setText("Manage Orders");
        btnManageOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrderActionPerformed(evt);
            }
        });

        btnManageManu1.setText("Set Discount");
        btnManageManu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageManu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageManu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageManu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnManageManu)
                .addGap(27, 27, 27)
                .addComponent(btnManageManu1)
                .addGap(33, 33, 33)
                .addComponent(btnManageOrder)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageManuActionPerformed
        // TODO add your handling code here:
        ManageRawFoodListJPanel panel = new ManageRawFoodListJPanel(system,superMarket,userProcessContainer);
        userProcessContainer.add("ManageRawFoodListJPanelJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageManuActionPerformed

    private void btnManageOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrderActionPerformed
        // TODO add your handling code here:
       SuperMarketOrdersJPanel panel = new SuperMarketOrdersJPanel(account,network,system,superMarket,userProcessContainer,streamOut);
        userProcessContainer.add("ManageOrdersJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrderActionPerformed

    private void btnManageManu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageManu1ActionPerformed

    ManageDiscountJPanel panel = new ManageDiscountJPanel(system,superMarket,userProcessContainer);
    userProcessContainer.add("ManageRawFoodListJPanelJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageManu1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageManu;
    private javax.swing.JButton btnManageManu1;
    private javax.swing.JButton btnManageOrder;
    // End of variables declaration//GEN-END:variables
}
